### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.zcmlhook#2]
According to https://pypi.org/project/z3c.zcmlhook/ @optilude is the only one who can release this package.

@optilude Could you please add me (`icemac`) at PyPI as owner for this package, so I can release #1 (official Python 3 support for this package) once the PR is merged?

**Comment by optilude** [comment]
Done!

**Comment by icemac** [comment]
@optilude Thank you for your immediate response.

**Comment by icemac** [comment]
Just released https://pypi.org/project/z3c.zcmlhook/1.1/
